Cargo.toml
src/adapter.rs

This change brings a file monitoring thread to control the binary runtime based on a file status.
A systemd path service can start this dab bridge on device but it will not be able to stop it when the file status changes.
The new thread will monitor for existence of /run/dab-enable file and if it gets deleted bridge will self-exit.

Added support for self-exit thread.

---

Cargo.lock
src/dab/structs.rs
src/device/rdk/applications/launch_with_content.rs

According to the latest DAB Specification 2.0.

applications/launch-with-content "parameters" req param is optional

---

src/adapter.rs
src/device/rdk/interface.rs

Prints RDK messages to stdout. Run as
cargo run -- -d my-rdk.ddns.net --debug=true

adapter: add debug option

---

src/device/rdk/applications/launch_with_content.rs

What :
-----------------------------------------
Adding fix for list-with-content
updating appId and response 
Why :
--------------------------------------------
api not working
appId is mismatching in check  and message field is not present in rdkresponse
getting error in the compliance suit.
How :
----------------------------------------------------------------
Added correct appId and remove unwanted field
Test :
---------------------------------------------------------------
Manually tested.
```
sam2@sam2-VirtualBox:~/RUST/dab-compliance-suite$ python3 main.py -v -b 127.0.0.1 -I 02AD320123DA -c ApplicationsLaunchWithContentConformance
testing applications/launch-with-content   {"appId": "YouTube", "contentId": "jfKfPfyJRdk"} ... App started with playback?(Y/N)
[Y] …
```

fix : fix for launching app with content.

---

src/device/rdk/applications/launch.rs
src/device/rdk/applications/launch_with_content.rs

What
------------------------------------------------------------------
fix for moving app to front from from suspended mode and second launch. 
fixing deeplink issue in launch-with-content.
Why
-----------------------------------------------------------------------------
Not able to see app on screen when launching from suspended mode/second time
How
----------------------------------------------------------------------------
Call movetofront/setfocus api call to move app to front on display
Test
-------------------------------------------------------------------------------
```
Tested scenarios:
1. ApplicationsLaunchConformance --->InputLongKeyPressKeyHome--->ApplicationsLaunchConformance
-------------> Launched----->Able to navigate
2. …
```

feat : Adding support for movetofront/setfocus.

---

src/adapter.rs
src/dab.rs
src/device/rdk/device/info.rs
src/device/rdk/interface.rs
src/device/rdk/system/settings/list.rs

```
$ dabSingleTest DeviceInfoConformance
testing device/info   {} ... 
device/info Latency, Expected: 200 ms, Actual: 1243 ms
device/info took more time than expected.
[ FAILED ]
{
"chipset": "Amlogic S905X4",
"deviceId": "487E489392DC",
"displayType": "External",
"firmwareBuild": "lib32-skyworth-generic-mediaclient-image_FBT_rdk-next_20231206080332",
"firmwareVersion": "MESONSC2-LIB32-AH212-HP44H-RDK/AML_SDK-BSP1019-RDK5.1.0-WPE_R4-NONB12-RW#SPIN=0",
"manufacturer": "Skyworth",
"model": "HP44H",
"networkInterfaces": [
{
"connected": false,
"dns": [],
"ipAddress": "",
"macAddress": "02:ad:32:01:a8:56",
"type": "Ethernet"
},
{
"connected": true,
"dns": [],
"ipAddress": "2601:41:c300:1bc0:4a7e:48ff:fe93:92dc",
"macAddress": "48:7e:48:93:92:dc",
"type": "Wifi"
}
],
"screenHeightPixels": …
```

Update device id in device/info, videoInputSource to HOME in system/settings/get (considering STB mode) and retire path from /run to /opt. 

---

src/device/rdk/applications/list.rs

```
$ python3 main.py -v -b DeviceIP -I DeviceID -c ApplicationsListConformance
testing applications/list   {} ... 
applications/list Latency, Expected: 200 ms, Actual: 59 ms
[ PASS ]
{
"applications": [
{
"appId": "PrimeVideo"
},
{
"appId": "YouTube"
}
],
"status": 200
}
```

Filtered applications/list to include only DAB-2.0 listed AppIDs.

---

Cargo.lock
Cargo.toml
src/device/rdk/applications/launch.rs
src/device/rdk/applications/launch_with_content.rs

What
----------------------------------------------------------
Adding fix to decode encoded parameters for youtube
Why
-----------------------------------------------------------------
As per dab-specification encoded url is given as parameter to youtube, but youtube accepts parameters in decoded string format
How
---------------------------------------------------------------
using urlencoding crate decoded the incoming parameter list for youtube before appening the parameter list

fix: decode encoded parameters for youtube playback

---

src/adapter.rs
src/device/rdk/interface.rs

This change helps debugging on error or abnormal behaviors from the log file itself instead of comparing the specific device stack/build.
- Added SHA print into log when the runtime starts which can be used to identify the build version from log.
- Added log to notify when any platform specific keymap override is detected.
**No platform keymap file**
```
Dec 15 02:58:06 AmlogicFirebolt systemd[1]: Started DAB <-> RDK adapter.
Dec 15 02:58:06 AmlogicFirebolt dab-adapter[24658]: DAB<->RDK Adapter [6f69b08b5ddc81b2df40f77147a01a91b396a6bd]
Dec 15 02:58:06 AmlogicFirebolt dab-adapter[24658]: Monitoring changes of /opt/dab-enable
Dec 15 02:58:07 AmlogicFirebolt dab-adapter[24658]: DAB Device ID: A09DC16EB2C6
Dec 15 02:58:07 AmlogicFirebolt dab-adapter[24658]: Ready to process DAB requests
Dec …
```

Added some support logs.

---

src/device/rdk/system/settings/get.rs
src/device/rdk/system/settings/list.rs

`/system/settings/list` doesn't report the current value of the mute switch, but the 'mute' value simply tells whether the device can be muted using `/system/settings/set` DAB function. It should probably be hardcoded to true for RDK.

Update mute value in /system/settings/list

---

src/device/rdk/interface.rs
src/device/rdk/system/settings/get.rs
src/device/rdk/system/settings/list.rs

This flag signifies whether CEC functionality is supported at all by the RDK device, not its current enabled or disabled state (that's what /system/settings/get is for).
Let's infer the availability of CEC from asking Thunder's Controller plugin if it recognizes org.rdk.HdmiCec_2 service.

Fix 'cec' field in /system/settings/list

---

src/device/rdk/applications/exit.rs
src/device/rdk/applications/launch.rs
src/device/rdk/applications/launch_with_content.rs
src/device/rdk/voice/send_audio.rs
src/device/rdk/voice/send_text.rs
src/device/rdk/voice/voice_functions.rs

This change includes the following:
1. Added poll for app state before sending response to the launch requests which is the requirement of DAB-2.0 spec. It will wait for 5 seconds to get the app state; else will return error.
2. As per DAB-2.0 https://github.com/device-automation-bus/dab-specification-2.0/blob/main/DAB.md#request-parameters-9, voiceSystem must be enabled which is odd. If the system is already enabled; then there is no need to enable again unless the requested voiceSystem is not the enabled one. Added a check to get enabled status before calling enable function. (Enabling a voice system may require time to reconfigure or switch the voice system endpoint which would take setup time.)
3. As per DAB-2.0 https://github.com/device-automation-bus/dab-specification-2.0/blob/main/D …

Align to DAB-2.0 specifications

---

src/device/rdk/system/settings/get.rs
src/device/rdk/system/settings/list.rs
src/device/rdk/system/settings/set.rs

Arun confirmed RDK has no APIs to control low latency on STBs. There's RDKDEV-934 requesting the missing APIs be added; until that ticket is implemented, let's return false when lowLatencyMode is listed or read.

system/settings: RDK doesn't support low latency setting

---

Cargo.toml
src/dab/structs.rs

Because dab_adapter::device::rdk::system::settings::set::process() now accepts SetSystemSettingsRequest structure, it will not only set the requested setting(s), but will also attempt to set ALL other settings to their default values.
Modify SetSystemSettingsRequest definition so that:
* its members are not initialized to their default values
* all members are optional
* members with None value are skipped during serialization

Fix system/settings/set

---

src/dab.rs

Without a valid Device ID; DAB functionality cannot progress. Triger Exit so that systemd can restart it again.

Triger EXIT if DeviceID is 'unknown'

---

src/device/rdk/system/settings/set.rs

If the sink/display is not supporting a set of resolution; API should return failure as it may not change the output as expected.
Here; the connected sink only supports the following:
```
{"supportedResolutions":["480p","720p60","1080i60","1080p24","1080p60"],"success":true}
```
**Compliance Suite Logs:**
```
d35@d35:~/Desktop/dab-works/dab-compliance-suite$ dabSingleTest SystemSettingsSetOutputresolution // Try setting 4K60
testing system/settings/set   {"outputResolution": {"width": 3840, "height": 2160, "frequency": 60} } ... [ 
Error: self.dab_client.last_error_code()
Internal error ]
{
"status": 500,
"error": "org.rdk.DisplaySettings.setCurrentResolution failed"
}
d35@d35:~/Desktop/dab-works/dab-compliance-suite$ 
d35@d35:~/Desktop/dab-works/dab-compliance-suite$ dabSingleTest …
```

Fix the issue of Setting unsupported resolution is returning success.

---

Cargo.lock
Cargo.toml
build.rs
src/adapter.rs
src/device/rdk/applications/list.rs

When dab-adapter starts; it will print the SEM_VER and GIT_SHORT_HASH also which is required to identify the runtime for debugging.
```
root@HP44HRDK:~# Mar 12 19:18:52 HP44HRDK systemd[1]: Started DAB <-> RDK adapter.
Mar 12 19:18:52 HP44HRDK dab-adapter[8924]: DAB<->RDK Adapter ("0.6.0" - "f488cae")
Mar 12 19:18:52 HP44HRDK dab-adapter[8924]: Monitoring changes of /opt/dab-enable
Mar 12 19:18:52 HP44HRDK dab-adapter[8924]: DAB Device ID: 02AD3201A856
Mar 12 19:18:53 HP44HRDK dab-adapter[8924]: Ready to process DAB requests
```

Add version and git hash support for debugging.

---

src/device/rdk/interface.rs

Moving config file path from `/tmp` to `/opt` - a persistent RW area in RDK devices.

Move dab_platform_app_lifecycle.json to persistent area

---

src/device/rdk/applications/launch.rs

Hello,
Currently it's not possible to resume (launch) any app from suspended (BACKGROUND) state. Any attempt produces an error:
Internal error
> { 
> "status": 500,
> "error": "Require App specific deeplinking implementation."
> }
> 
which comes from lines 161-166:
```
} else {
// Other App specific deeplinking.
return Err(DabError::Err500(
"Require App specific deeplinking implementation.".to_string(),
));
}
```
Thanks!

Fix launching Netflix from suspended state

---

src/dab/device_telemetry.rs
src/dab/mqtt_client.rs
src/device/rdk/interface.rs
src/device/rdk/operations/list.rs

**Description:**
Update DeviceTelemetry logic to add both memory and cpu statistics.
Since its marked as an optional one; hide from operations/list.
**Test Details:**
Compliance Suite
```
testing device-telemetry/start   {"duration": 1000} ... 
device-telemetry/start Latency, Expected: 200 ms, Actual: 41 ms
[ PASS ]
{
"duration": 1000,
"status": 200
}
testing device-telemetry/stop   {} ... 
device-telemetry/stop Latency, Expected: 200 ms, Actual: 1521 ms
device-telemetry/stop took more time than expected.
[ FAILED ]
{
"status": 200
}
```
MQTTListener:
```
d35@d35:~/Desktop/dab-compliance-suite$ mosquitto_sub -h 10.0.0.88 -v -t '#' | ts '[%Y%b%d %H:%M:%.S]'
[2024Apr01 20:45:27.049194] dab/02AD3201C835/device-telemetry/start {"duration": 1000}
[2024Apr01 20:45:27.060563] …
```

Update DeviceTelemetry logic

---

src/device/rdk/interface.rs

For example
get_thunder_property("DeviceInfo.serialnumber", "serialnumber")?
correctly returned "320b0202000000000e18c04115b05600", but when the function was called with an empty key_name:
get_thunder_property("DisplayInfo.framerate", "")?
it returned "\"Framerate60\"" instead of "Framerate60".

Fix extra quotation marks around get_thunder_property() results

---

src/dab.rs
src/device/rdk/applications/exit.rs
src/device/rdk/applications/get_state.rs
src/device/rdk/applications/launch.rs
src/device/rdk/applications/launch_with_content.rs
src/device/rdk/interface.rs

This change tries to address the issues mentioned in https://github.com/device-automation-bus/dab-adapter-rs/issues/55
> 1. There is a function get_app_state in get_state.rs file but there are also at least three copies of full implementations to get app state in exit.rs, luanch.rs and launch_with_content.rs with multiple strings manipulations beyond that. The suggestion is to have just one function for that purpose to get app state which returns enum value.
Changed the logic to map to DAB app state and used that to derive the required functionalities.
> 2. Boolean variables app_created and is_suspended in those files are just emulation of tri-state app status we're getting from RDKShell. To get the correct state of the app the code in general should check both variables at the same time. …

Refactor app state logic (launch and exit)

---

src/device/rdk/applications/launch.rs
src/device/rdk/applications/launch_with_content.rs

Visibility and focus can be set only if app is created not before.
Focus can be set if app is visible.
After that change I see less error reporting from RDKShell when suspending/resuming apps.
@arun-madhavan-013 and @denisyuji please review the change.

Corrected launching the apps

---

src/device/rdk/system/settings/list.rs

Reason for change: some platform supports multiple audioport hence updating list. "IDLR0" => Aux,"SPEAKER0" => NativeSpeaker.
Test Procedure: build,flash image and verify DAB settings/list operation .
Risks: Medium.

BCM-1152: Updating Supported audioOutputSource List.

---

src/device/rdk/interface.rs

Cache device id to improve performance of the device/info request and pass the DeviceInfoConformance test case.

PREMIUMAPP-3148: Cache device id

---

src/device/rdk/interface.rs

Load the default keymap from /etc/dab/keymap.json or use the built-in keymap if it is not available.

PREMIUMAPP-3146: Load default keymap from file

---

README.md
src/device/rdk/applications/launch.rs
src/device/rdk/interface.rs
src/device/rdk/system/settings/get.rs
src/device/rdk/system/settings/list.rs

The goal of this PR is to:
- enable YTS test cases that rely on multiple languages,
- for Cobalt, start the application with chosen UI language.
To achieve this, instead of having hard-coded language code in `src/device/rdk/system/settings/list.rs`, allow user to create a configuration file in `/etc/dab/settings.json` where a list of supported languages might be provided (using en-US if not found or failed to parse).  For starting a Cobalt application with proper language, during launch command a call to UserPreferences is issued, to retrieve currently used language. That language is later used in `language` parameter for Cobalt application. 
Configuration file, with a support for two languages could look like following:
```
{
"supported_languages": ["en-US", "es-US"]
}
```

[PREMIUMAPP-3286] Introduce support for multiple UI languages

---

src/dab/structs.rs
src/device/rdk/voice/send_audio.rs
src/device/rdk/voice/send_text.rs
src/device/rdk/voice/set.rs

When VA is not supported by the platform, and the VA is set to "" in compliance-suite tool, it is sending requests with:  `"voiceSystem": ""`. In that  case, fail-fast with 400 status code nad avoid initialization of misconfigured voice system.

PREMIUMAPP-3387: Check for empty VA to return 400 and avoid initializing not supported VA

---

src/device/rdk/operations/list.rs

This API was tested by dab-compliance-suite previously, although it was not in the operations/list. On latest compliance-suite: c77884c7a1a516e43c6e8ed057508121f8f368dc this value is actually checked and taken into account.

RDKEAPPRT-108: Enable input/long-key-press in operations/list output
